package cfd_trading_club::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'cfd_trading_club::Schema',

    connect_info => {
        dsn => 'dbi:Pg:dbname=cfd_trading_club',
        user => '',
        password => '',
    }
);

my %confidence_levels = (
    1 => 'Complete guess',
    2 => 'Quietly confident',
    3 => 'You\'d bet your left testicle',
    4 => 'You\'d bet both of your testicles',
    5 => 'You feel like a Japanese Sensei',
);

sub get_confidence_levels {
    my $self = shift;
    return \%confidence_levels;
}

=head1 NAME

cfd_trading_club::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<cfd_trading_club>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<cfd_trading_club::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Zane Moser

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
