package cfd_trading_club::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'cfd_trading_club::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=cfd_trading_club',
        user => '',
        password => '',
    }
);

=head1 NAME

cfd_trading_club::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<cfd_trading_club>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<cfd_trading_club::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Zane Moser

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
